### PR TITLE
chore: update traefik to v2.5.0

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

https://github.com/eclipse/che/issues/20142

### CODE REVIEW

**Comment by sparkoo** [comment]
ATM there is still no x86 image for v2.5.0 https://hub.docker.com/layers/traefik/library/traefik/v2.5.0/images/sha256-9506435ce3d83eb9c00ffab7a98a144e06b52fe7b8af47a9fda7e1b344e30192?context=explore it is building https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/

**Comment by nickboldt** [comment]
lmk when the upstream image exists and I can run the copy script.

also, will this image be REPLACING 2.3.2 in Che 7.35.x or 7.36? Or will it be in addition to 2.3.2? 

Same question for CRW -- do I need to update our crw-traefik build to include ONLY 2.5.0, or is this in addition to 2.3.2?

**Comment by sparkoo** [comment]
we will have only single version of traefik again, which now will be 2.5.0. Followup PR in che-operator will come soon, so it should be included in next release.

**Comment by sparkoo** [comment]
@nickboldt I can see x86 traefik image there. So please fire at will.

**Comment by nickboldt** [comment]
copied to quay.io/eclipse/che--traefik:v2.5.0-eb30f9f09a65cee1fab5ef9c64cb4ec91b800dc3fdd738d62a9d4334f0114683

**Comment by nickboldt** [comment]
downstream work in https://issues.redhat.com/browse/CRW-2178

**Pull request merged**
